Bugfix/4-1 日付フォーマットの変更、従業員一覧の並び順
sakana3F/ex-emp-management-bugfix pull request #4
Opened 2024-11-25 08:12 UTC by sakana3F

【従業員一覧ページ】
3-1：従業員一覧の並び順
入社日が新しい順、アドレスの昇順で表示するように変更しました。
3-2：日付フォーマット
「yyyy/mm/dd」→「yyyy年mm月dd日」

【従業員詳細ページ】
4-1：日付フォーマット
「yyyy/mm/dd」→「yyyy年mm月dd日」

前回送ったbranchの変更内容が私が思っていた内容と違ったみたいです。すみません。
把握があいまいになってしまったので今回の4-1で、3-1,3-2,4-1の変更がまとまってます！
大変申し訳ないのですがまとめてご確認お願いします。

2024-11-25 08:27 UTC, mokichi42 requested changes
修正お願いします！

2024-11-25 08:27 UTC, mokichi42 commented on src/main/resources/templates/employee/detail.html
Date型のデータをThymeleaf側で変更する形にしましょう

2024-11-25 08:27 UTC, mokichi42 commented on src/main/resources/templates/employee/list.html
こちらもDate型のデータをThymeleaf側で変更する形にしましょう

2024-11-26 00:09 UTC, sakana3F commented on src/main/resources/templates/employee/list.html
承知しました。

2024-11-26 00:14 UTC, sakana3F commented on src/main/resources/templates/employee/list.html
Thymeleaf側で変更する形に修正しましたので確認お願いいたします！

2024-11-26 00:35 UTC, mokichi42 approved these changes
OKです！

2024-11-26 00:35 UTC, merged

2024-11-26 00:55 UTC, sakana3F commented
ご確認ありがとうございます！